app/accounts/urls.py
from django.contrib import admin
from django.urls import path

from accounts.views import LoginView, logout_view, RegisterView, DeleteUser
from webapp.views import *

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('user/delete', DeleteUser.as_view(), name='delete_user')
]

app/app/urls.py
from django.contrib import admin
from django.urls import path

from webapp.views import *
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('<int:pk>/', TaskView.as_view(), name='task_view'),
    path('add/', TaskCreate.as_view(), name='add'),
    path('edit/<int:pk>/', TaskUpdate.as_view(), name='edit'),
    path('delete/<int:pk>/', TaskDelete.as_view(), name='delete'),
    path('projects', ProjectView.as_view(), name='projects'),
    path('project/<int:pk>', ProjectDetailView.as_view(), name='project_view'),
    path('project/update/<int:pk>', UpdateProject.as_view(), name='project_update'),

    path("accounts/", include('accounts.urls'))
]

app/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label='Логин')
    password = forms.CharField(required=True, label='Пароль', widget=forms.PasswordInput)


class CustomUserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', strip=False, required=True,
                               widget=forms.PasswordInput(attrs={'class': 'input'}))
    password_confirm = forms.CharField(label='Подтвердите пароль', strip=False, required=True,
                                       widget=forms.PasswordInput(attrs={'class': 'input'}))

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if len(first_name) == 0:
            raise ValidationError('Поле имени не заполнено')
        return first_name

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'input'}),
            'first_name': forms.TextInput(attrs={'class': 'input'}),
            'last_name': forms.TextInput(attrs={'class': 'input'}),
            'email': forms.EmailInput(attrs={'class': 'input', 'required': True})
        }

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise ValidationError('Пароли не совпадают')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

app/accounts/views.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

from accounts.forms import LoginForm, CustomUserCreationForm
from webapp.models import Project


class LoginView(TemplateView):
    template_name = "login.html"
    form = LoginForm

    def get(self, request, *args, **kwargs):
        form = self.form()
        context = {'form': form}
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if not form.is_valid():
            return redirect('index')
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if not user:
            return redirect('login')
        login(request, user)
        return redirect('index')


def logout_view(request):
    logout(request)
    return redirect('index')


class RegisterView(CreateView):
    template_name = 'register.html'
    form_class = CustomUserCreationForm

    success_url = 'index'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        context = {}
        context['form'] = form
        return self.render_to_response(context)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('index')
        return next_url


class DeleteUser(DeleteView):
    template_name = 'delete_user.html'
    model = User

app/accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block header_block %}
{% endblock %}
{% block title %}Задачи{% endblock %}
{% block todo_block %}
<div class="todo_head">
    <div class="head_block">
        <h2 class="task_title">Вход</h2>
    </div>
</div>
<div class="todo_body">
    <form class="todo_form" action="{% url 'login' %}" method="POST">
        {% csrf_token %}

        {% if has_error %}
        <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <p>
            <label class="form_label" for="username">Имя пользователя:
                <input required class="input" type="text" name="username" id="username">
            </label>
        </p>
        <p>
            <label class="form_label" for="password">Пароль:
                <input required class="input" type="password" name="password" id="password"></label>

            <button class="btn green" type="submit">Войти</button>
        </p>
    </form>
</div>
{% endblock %}

app/accounts/templates/register.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap5 %}
{% block header_block %}
{% endblock %}
{% block title %}Задачи{% endblock %}
{% block todo_block %}
<div class="todo_head">
    <div class="head_block">
        <h2 class="task_title">Регистрация</h2>
    </div>
</div>
<div class="todo_body">
    <form class="todo_form" action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        <p>
            <label class="form_label" for="username">Имя пользователя:
                <input required class="input" type="text" name="username" id="username">
            </label>
        </p>
        <p>
            <label class="form_label" for="password">Пароль:
                <input required class="input" type="password" name="password" id="password"></label>
        <div class="form-error">
            {{form.password.errors}}
        </div>
        </p>
        <p>
            <label class="form_label" for="id_password_confirm">Подтвердите пароль:
                <input required class="input" type="password" name="password_confirm" id="id_password_confirm"></label>
        </p>
        <p>
            <label class="form_label" for="id_first_name">Имя:
                <input class="input" type="text" name="first_name" id="id_first_name"></label>
        <div class="form-error">
            {{form.first_name.errors}}
        </div>
        </p>
        <p>
            <label class="form_label" for="id_last_name">Фамилия:
                <input class="input" type="text" name="last_name" id="id_last_name"></label>
        </p>
        <p>
            <label class="form_label" for="id_email">Email:
                <input required class="input" type="email" name="email" id="id_email"></label>
        </p>

        <button class="btn green" type="submit">Регистрация</button>
    </form>
</div>
{% endblock %}